name: ci-workflow
on:
  pull_request:
    branches:
      - develop
    pull_request:
      types:
        - opened
        - synchronize
        - reopened
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm --prefix integracao-continua ci
      - run: npm --prefix integracao-continua test -- --coverage
      - uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
